# Generated by Django 5.0.1 on 2024-02-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, unique=True)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("editing_datetime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Key",
                "verbose_name_plural": "Keys",
                "db_table": "sample_key",
            },
        ),
    ]
